version: '3.7'

networks:
  default:

volumes:
  pgdata:

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: larademo
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 8081:80
    networks:
      - default
    depends_on:
      - postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: larademo
    image: devilas/larademo:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: larademo
      DB_USERNAME: postgres
      DB_PASSWORD: xyz999
    networks:
      - default
    depends_on:
      - postgres
